#!/bin/bash


sudo docker run -it --network=host --device=/dev/kfd --device=/dev/dri --ipc=host --shm-size 16G --group-add video --cap-add=SYS_PTRACE --security-opt seccomp=unconfined -v $(pwd):/workspace -v $HOME/Documents/datasets:/datasets -e DATASET_DIR=/datasets rocm/tensorflow:rocm3.3-tf2.1-dev


